import { AdminControls, AdminSettingForm, AdminWithdrawalControl } from "@/components/admin-controls";

const money = (value: number) => `${value.toLocaleString("fr-FR")} FCFA`;
type Props = { users: { id: string; full_name: string | null; referral_code: string; suspended_at: string | null }[]; withdrawals: { id: string; amount: number; status: string }[]; settings: { key: string; value: unknown }[]; referrals: number; rewards: number; fraudEvents: number; logs: { action: string; entity_type: string; created_at: string }[] };

export function AdminDashboard({ users, withdrawals, settings, referrals, rewards, fraudEvents, logs }: Props) {
    const setting = (key: string, fallback: number | boolean) => { const value = settings.find((item) => item.key === key)?.value; return typeof value === "number" || typeof value === "boolean" ? value : fallback; };
    const metrics: [string, number][] = [["Utilisateurs", users.length], ["Referrals", referrals], ["Transactions", rewards], ["Fraudes ouvertes", fraudEvents]];
    const configurable: [string, number | boolean][] = [["signup_bonus", setting("signup_bonus", 1000)], ["referral_bonus", setting("referral_bonus", 500)], ["withdrawal_threshold", setting("withdrawal_threshold", 15000)], ["qualification_min_visits", setting("qualification_min_visits", 1)], ["qualification_require_email", setting("qualification_require_email", true)]];
    return <><section className="mt-12 grid gap-4 md:grid-cols-4">{metrics.map(([label, value]) => <div key={label} className="border border-[#d9d7cb] p-5"><p className="eyebrow">{label}</p><p className="mt-6 text-3xl">{value}</p></div>)}</section><section className="mt-16 grid gap-12 lg:grid-cols-2"><div><p className="eyebrow">Utilisateurs</p><div className="mt-4 divide-y divide-[#d9d7cb] border-y border-[#d9d7cb]">{users.map((item) => <div key={item.id} className="flex justify-between gap-4 py-4 sans text-sm"><span>{item.full_name || item.id.slice(0, 8)}<small className="block text-[#66705f]">{item.referral_code}</small></span><AdminControls userId={item.id} suspended={Boolean(item.suspended_at)} /></div>)}</div></div><div><p className="eyebrow">Retraits à traiter</p><div className="mt-4 divide-y divide-[#d9d7cb] border-y border-[#d9d7cb]">{withdrawals.length ? withdrawals.map((item) => <div key={item.id} className="flex justify-between gap-4 py-4 sans text-sm"><span>{money(item.amount)}<small className="block text-[#66705f]">{item.status}</small></span><AdminWithdrawalControl withdrawalId={item.id} status={item.status} /></div>) : <p className="py-5 sans text-sm text-[#66705f]">Aucun retrait en attente.</p>}</div></div><div><p className="eyebrow">Paramètres</p><div className="mt-4 grid gap-4 sans text-sm">{configurable.map(([key, value]) => <div key={key} className="flex items-center justify-between border-b border-[#d9d7cb] py-3"><span>{key}</span><AdminSettingForm settingKey={key} value={value} /></div>)}</div></div><div><p className="eyebrow">Journal d’audit</p><div className="mt-4 divide-y divide-[#d9d7cb] border-y border-[#d9d7cb]">{logs.map((log) => <div key={log.created_at + log.action} className="py-3 sans text-xs"><strong>{log.action}</strong><span className="ml-3 text-[#66705f]">{log.entity_type} · {new Date(log.created_at).toLocaleString("fr-FR")}</span></div>)}</div></div></section></>;
}
