import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { ReferralPanel } from "@/components/referral-panel";

const money = (value: number) => `${value.toLocaleString("fr-FR")} FCFA`;
export default async function Dashboard() {
    if (!process.env.NEXT_PUBLIC_SUPABASE_URL || !process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY) return <main className="mx-auto max-w-2xl px-5 py-24"><p className="eyebrow">Configuration requise</p><h1 className="mt-5 text-5xl">Connectez Supabase pour ouvrir votre espace.</h1><p className="sans mt-6 text-[#66705f]">Renseignez les variables d’environnement documentées dans `.env.example`, puis appliquez les migrations.</p></main>;
    const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/connexion");
    const [{ data: profile }, { data: wallet }, { data: rewards }, { data: referrals }, { data: withdrawals }] = await Promise.all([
        supabase.from("profiles").select("full_name, referral_code").eq("id", user.id).single(), supabase.from("wallets").select("balance").eq("user_id", user.id).single(), supabase.from("reward_transactions").select("amount, kind, note, created_at").eq("user_id", user.id).order("created_at", { ascending: false }).limit(20), supabase.from("referrals").select("id, referred_id, qualified_at, created_at").eq("sponsor_id", user.id).order("created_at", { ascending: false }), supabase.from("withdrawals").select("amount, status, created_at").eq("user_id", user.id).order("created_at", { ascending: false }).limit(20),
    ]);
    const balance = wallet?.balance ?? 0; const qualified = referrals?.filter((item) => item.qualified_at).length ?? 0; const referralGains = rewards?.filter((item) => item.kind === "REFERRAL_BONUS").reduce((sum, item) => sum + item.amount, 0) ?? 0; const progress = Math.min(100, Math.round((balance / 15000) * 100));
    return <main className="mx-auto max-w-7xl px-5 py-12 md:px-10"><div className="flex flex-col justify-between gap-5 border-b border-[#d9d7cb] pb-8 md:flex-row md:items-end"><div><p className="eyebrow">Espace membre</p><h1 className="mt-4 text-5xl">Bonjour{profile?.full_name ? `, ${profile.full_name}` : ""}.</h1></div><form action="/auth/signout" method="post"><button className="sans text-sm font-bold underline">Se déconnecter</button></form></div><section className="grid gap-4 py-10 md:grid-cols-4"><div className="bg-[#c8ef62] p-5"><p className="eyebrow">Solde disponible</p><p className="mt-6 text-3xl">{money(balance)}</p></div><div className="border border-[#d9d7cb] p-5"><p className="eyebrow">Avant retrait</p><p className="mt-6 text-3xl">{money(Math.max(0, 15000 - balance))}</p></div><div className="border border-[#d9d7cb] p-5"><p className="eyebrow">Filleuls</p><p className="mt-6 text-3xl">{referrals?.length ?? 0}</p></div><div className="border border-[#d9d7cb] p-5"><p className="eyebrow">Qualifiés</p><p className="mt-6 text-3xl">{qualified}</p></div></section><section className="grid gap-12 lg:grid-cols-[1fr_1fr]"><div><p className="eyebrow">Progression vers 15 000 FCFA</p><div className="mt-5 h-3 bg-[#d9d7cb]"><div className="h-full bg-[#ff7657]" style={{ width: `${progress}%` }} /></div><p className="sans mt-3 text-sm text-[#66705f]">{progress}% · {money(balance)} accumulés</p><div className="mt-10"><p className="eyebrow">Votre parrainage</p><div className="mt-4"><ReferralPanel code={profile?.referral_code ?? ""} siteUrl={process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000"} /></div><p className="sans mt-4 text-sm text-[#66705f]">Gains de parrainage : {money(referralGains)}</p></div></div><div><p className="eyebrow">Transactions récentes</p><div className="mt-4 divide-y divide-[#d9d7cb] border-y border-[#d9d7cb]">{rewards?.length ? rewards.map((reward) => <div key={reward.created_at + reward.kind} className="flex justify-between gap-4 py-4 sans text-sm"><span>{reward.note ?? reward.kind}</span><strong>{reward.amount > 0 ? "+" : ""}{money(reward.amount)}</strong></div>) : <p className="py-5 sans text-sm text-[#66705f]">Aucune transaction.</p>}</div><p className="eyebrow mt-10">Retraits récents</p><div className="mt-4 divide-y divide-[#d9d7cb] border-y border-[#d9d7cb]">{withdrawals?.length ? withdrawals.map((withdrawal) => <div key={withdrawal.created_at} className="flex justify-between py-4 sans text-sm"><span>{withdrawal.status}</span><strong>{money(withdrawal.amount)}</strong></div>) : <p className="py-5 sans text-sm text-[#66705f]">Aucun retrait.</p>}</div><Link href="/retraits" className="sans mt-5 inline-block text-sm font-bold underline">Voir les règles de retrait →</Link></div></section></main>;
}
